# Generated by Django 3.1.5 on 2021-02-05 16:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('braceconfig', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='brace_five',
            field=models.IntegerField(blank=True, help_text='Brace 5', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='brace_four',
            field=models.IntegerField(blank=True, help_text='Brace 4', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='brace_one',
            field=models.IntegerField(blank=True, help_text='Brace 1', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='brace_six',
            field=models.IntegerField(blank=True, help_text='Brace 6', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='brace_three',
            field=models.IntegerField(blank=True, help_text='Brace 3', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='brace_two',
            field=models.IntegerField(blank=True, help_text='Brace 2', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this patient', primary_key=True, serialize=False),
        ),
    ]
