# Generated by Django 3.1.5 on 2021-02-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('braceconfig', '0002_auto_20210205_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='brace_five',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='brace_four',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='brace_one',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='brace_six',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='brace_three',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='brace_two',
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
