# Generated by Django 3.1.5 on 2021-02-26 06:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('braceconfig', '0003_auto_20210226_0047'),
    ]

    operations = [
        migrations.CreateModel(
            name='RxInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique Prescription ID', primary_key=True, serialize=False)),
                ('brace_one', models.IntegerField(blank=True, help_text='Brace 1', null=True)),
                ('brace_two', models.IntegerField(blank=True, help_text='Brace 2', null=True)),
                ('brace_three', models.IntegerField(blank=True, help_text='Brace 3', null=True)),
                ('brace_four', models.IntegerField(blank=True, help_text='Brace 4', null=True)),
                ('brace_five', models.IntegerField(blank=True, help_text='Brace 5', null=True)),
                ('brace_six', models.IntegerField(blank=True, help_text='Brace 6', null=True)),
                ('status', models.CharField(blank=True, choices=[('a', 'Ongoing'), ('r', 'Resolved')], default='m', help_text='Prescription Ongoing', max_length=1)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='braceconfig.patient')),
            ],
            options={
                'ordering': ['status'],
            },
        ),
    ]
