# Generated by Django 3.1.5 on 2021-03-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('braceconfig', '0004_rxinstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='height',
            field=models.IntegerField(help_text='Height', max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='weight',
            field=models.IntegerField(help_text='Weight', max_length=200),
        ),
    ]
